/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Order.h
 *
 * An order for a pets from the pet store
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Order_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Order_H_


#include <nlohmann/json.hpp>

#include "CppLibcurlOpenAPIClient/ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// An order for a pets from the pet store
/// </summary>
class  Order
    : public ModelBase {
public:
    Order();
    virtual ~Order() = default;

    /////////////////////////////////////////////
    /// ModelBase overrides
    nlohmann::json toJson() const override;
    bool fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Order members

    /// <summary>
    /// 
    /// </summary>
    int64_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(int64_t value);

    /// <summary>
    /// 
    /// </summary>
    int64_t getPetId() const;
    bool petIdIsSet() const;
    void unsetPetId();

    void setPetId(int64_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getQuantity() const;
    bool quantityIsSet() const;
    void unsetQuantity();

    void setQuantity(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    const std::string& getShipDate() const;
    bool shipDateIsSet() const;
    void unsetShipDate();

    void setShipDate(const std::string& value);

    /// <summary>
    /// Order Status
    /// </summary>
    const std::string& getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const std::string& value);

    /// <summary>
    /// 
    /// </summary>
    bool isComplete() const;
    bool completeIsSet() const;
    void unsetComplete();

    void setComplete(bool value);


protected:
    int64_t m_Id;
    bool m_IdIsSet;
    int64_t m_PetId;
    bool m_PetIdIsSet;
    int32_t m_Quantity;
    bool m_QuantityIsSet;
    std::string m_ShipDate;
    bool m_ShipDateIsSet;
    std::string m_Status;
    bool m_StatusIsSet;
    bool m_Complete;
    bool m_CompleteIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Order_H_ */
