/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Pet.h
 *
 * A pet for sale in the pet store
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Pet_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Pet_H_


#include <nlohmann/json.hpp>

#include "CppLibcurlOpenAPIClient/ModelBase.h"

#include <string>
#include "CppLibcurlOpenAPIClient/model/Category.h"
#include <vector>
#include "CppLibcurlOpenAPIClient/model/Tag.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Category;
class Tag;

/// <summary>
/// A pet for sale in the pet store
/// </summary>
class  Pet
    : public ModelBase {
public:
    Pet();
    virtual ~Pet() = default;

    /////////////////////////////////////////////
    /// ModelBase overrides
    nlohmann::json toJson() const override;
    bool fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// Pet members

    /// <summary>
    /// 
    /// </summary>
    int64_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(int64_t value);

    /// <summary>
    /// 
    /// </summary>
    const std::shared_ptr<Category>& getCategory() const;
    bool categoryIsSet() const;
    void unsetCategory();

    void setCategory(const std::shared_ptr<Category>& value);

    /// <summary>
    /// 
    /// </summary>
    const std::string& getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const std::string& value);

    /// <summary>
    /// 
    /// </summary>
    const std::vector<std::string>& getPhotoUrls() const;
    bool photoUrlsIsSet() const;
    void unsetPhotoUrls();

    void setPhotoUrls(const std::vector<std::string>& value);

    /// <summary>
    /// 
    /// </summary>
    const std::vector<std::shared_ptr<Tag>>& getTags() const;
    bool tagsIsSet() const;
    void unsetTags();

    void setTags(const std::vector<std::shared_ptr<Tag>>& value);

    /// <summary>
    /// pet status in the store
    /// </summary>
    const std::string& getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const std::string& value);


protected:
    int64_t m_Id;
    bool m_IdIsSet;
    std::shared_ptr<Category> m_Category;
    bool m_CategoryIsSet;
    std::string m_Name;
    bool m_NameIsSet;
    std::vector<std::string> m_PhotoUrls;
    bool m_PhotoUrlsIsSet;
    std::vector<std::shared_ptr<Tag>> m_Tags;
    bool m_TagsIsSet;
    std::string m_Status;
    bool m_StatusIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Pet_H_ */
