/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * User.h
 *
 * A User who is purchasing from the pet store
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_User_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_User_H_


#include <nlohmann/json.hpp>

#include "CppLibcurlOpenAPIClient/ModelBase.h"

#include <string>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// A User who is purchasing from the pet store
/// </summary>
class  User
    : public ModelBase {
public:
    User();
    virtual ~User() = default;

    /////////////////////////////////////////////
    /// ModelBase overrides
    nlohmann::json toJson() const override;
    bool fromJson(const nlohmann::json& json) override;

    /////////////////////////////////////////////
    /// User members

    /// <summary>
    /// 
    /// </summary>
    int64_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(int64_t value);

    /// <summary>
    /// 
    /// </summary>
    const std::string& getUsername() const;
    bool usernameIsSet() const;
    void unsetUsername();

    void setUsername(const std::string& value);

    /// <summary>
    /// 
    /// </summary>
    const std::string& getFirstName() const;
    bool firstNameIsSet() const;
    void unsetFirstName();

    void setFirstName(const std::string& value);

    /// <summary>
    /// 
    /// </summary>
    const std::string& getLastName() const;
    bool lastNameIsSet() const;
    void unsetLastName();

    void setLastName(const std::string& value);

    /// <summary>
    /// 
    /// </summary>
    const std::string& getEmail() const;
    bool emailIsSet() const;
    void unsetEmail();

    void setEmail(const std::string& value);

    /// <summary>
    /// 
    /// </summary>
    const std::string& getPassword() const;
    bool passwordIsSet() const;
    void unsetPassword();

    void setPassword(const std::string& value);

    /// <summary>
    /// 
    /// </summary>
    const std::string& getPhone() const;
    bool phoneIsSet() const;
    void unsetPhone();

    void setPhone(const std::string& value);

    /// <summary>
    /// User Status
    /// </summary>
    int32_t getUserStatus() const;
    bool userStatusIsSet() const;
    void unsetUserStatus();

    void setUserStatus(int32_t value);


protected:
    int64_t m_Id;
    bool m_IdIsSet;
    std::string m_Username;
    bool m_UsernameIsSet;
    std::string m_FirstName;
    bool m_FirstNameIsSet;
    std::string m_LastName;
    bool m_LastNameIsSet;
    std::string m_Email;
    bool m_EmailIsSet;
    std::string m_Password;
    bool m_PasswordIsSet;
    std::string m_Phone;
    bool m_PhoneIsSet;
    int32_t m_UserStatus;
    bool m_UserStatusIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_User_H_ */
