/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "CppLibcurlOpenAPIClient/Utility.h"

#include <string>
#include <string_view>

namespace org {
namespace openapitools {
namespace client {
namespace api {

void replaceAll(std::string &str, std::string_view what,
                std::string_view with) {
    for (std::string::size_type pos{};
        (pos = str.find(what.data(), pos, what.length())) != str.npos;
        pos += with.length()) {
        str.replace(pos, what.length(), with.data(), with.length());
    }
}

}
}
}
}
