/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#include "CppLibcurlOpenAPIClient/Utility.h"

#include <string>
#include <string_view>

namespace org::openapitools::client::api {

void replaceAll(std::string &str, std::string_view what,
                std::string_view with) {
    auto pos = str.find(what);

    while (pos != std::string::npos) {
        str.replace(pos, what.length(), with);
        pos = str.find(what, pos + with.length());
    }
}

}
