/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "CppLibcurlOpenAPIClient/model/Category.h"

namespace org::openapitools::client::model {



nlohmann::json Category::toJson() const {
    nlohmann::json val = nlohmann::json::object();
    
    if (m_IdIsSet) {
        val["id"] = ModelBase::toJson(m_Id);
    }
    if (m_NameIsSet) {
        val["name"] = ModelBase::toJson(m_Name);
    }

    return val;
}

bool Category::fromJson(const nlohmann::json& val) {
    bool ok = true;
    
    if (val.contains("id")) {
        const nlohmann::json& fieldValue = val.at("id");
        if (!fieldValue.is_null()) {
            int64_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if (val.contains("name")) {
        const nlohmann::json& fieldValue = val.at("name");
        if (!fieldValue.is_null()) {
            std::string refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    return ok;
}

int64_t Category::getId() const {
    return m_Id;
}

void Category::setId(int64_t value) {
    m_Id = value;
    m_IdIsSet = true;
}

bool Category::idIsSet() const {
    return m_IdIsSet;
}

void Category::unsetId() {
    m_IdIsSet = false;
}
const std::string& Category::getName() const {
    return m_Name;
}

void Category::setName(std::string_view value) {
    m_Name = value;
    m_NameIsSet = true;
}

bool Category::nameIsSet() const {
    return m_NameIsSet;
}

void Category::unsetName() {
    m_NameIsSet = false;
}
}


