/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ApiConfiguration.h
 *
 * Configuration for API Client.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ApiConfiguration_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ApiConfiguration_H_



#include <map>
#include <string>

namespace org {
namespace openapitools {
namespace client {
namespace api {

class  ApiConfiguration {
public:
    virtual ~ApiConfiguration() = default;

    const std::string &getBaseUrl() const;
    void setBaseUrl(const std::string &value);

    const std::string &getClientCert() const;
    void setClientCert(const std::string &value);

    const std::string &getClientKey() const;
    void setClientKey(const std::string &value);

    const std::string &getCACert() const;
    void setCACert(const std::string &value);

    bool getSkipTlsVerify() const;
    void setSkipTlsVerify(bool value);

    const std::map<std::string, std::string> &getApiKeys() const;
    void setApiKeys(const std::map<std::string, std::string> &value);
    const std::string &getAccessToken() const;
    void setAccessToken(const std::string &value);

protected:
    std::string m_BaseUrl;
    std::string m_ClientCertFile; /* client certificate */
    std::string m_ClientKeyFile;  /* client private key */
    std::string m_CACertFile;     /* CA certificate */
    bool m_SkipTlsVerify{false};  /* false -- verify server certificate */
                                  /* true -- skip ssl verify for server certificate */

    std::map<std::string, std::string> m_ApiKeys;
    std::string m_AccessToken;
};

}
}
}
}
#endif /* ORG_OPENAPITOOLS_CLIENT_API_ApiConfiguration_H_ */
