/**
 * OpenAPI Petstore
 * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.2.1-SNAPSHOT.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Utility.h
 *
 * Utility functions.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_Utility_H_
#define ORG_OPENAPITOOLS_CLIENT_API_Utility_H_

#include <string>
#include <string_view>

namespace org::openapitools::client::api {

void replaceAll(std::string &str, std::string_view what, std::string_view with);

}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_Utility_H_ */
